cylc/cylc-rose

- cylc/rose/jinja2_parser.py
- cylc/rose/rose.py
- tests/test_config_node.py
- tests/test_config_tree.py
sibling: https://github.com/metomi/rose/pull/2430
Catch literal_eval errors and wrap them with `ConfigProcessError` to provide a more helpful error message.
Once #9 is done only the last line will appear in the Cylc command line output.
*Example:*
```ini
[jinja2:suite.rc]
X=Y
```
*Before:*
```
Traceback (most recent call last):
...
ValueError: malformed node or string: <_ast.Name object at 0x7f9c43c95ed0>
```
*After:*
```
Traceback (most recent call last):
...
metomi.rose.config_processor.ConfigProcessError: jinja2:suite.rc=Y=X: Invalid template variable: X
Must be a valid Python or Jinja2 literal (note strings "must be quoted").
```
> catch literal_eval errors

- cylc/rose/utilities.py
- tests/functional/09_template_vars_vanilla/flow.cylc
- tests/functional/09_template_vars_vanilla/processed.conf.control
- tests/functional/09_template_vars_vanilla/rose-suite.conf
- tests/functional/test_pre_configure.py
This PR plus [Cylc-flow PR 4073](https://github.com/cylc/cylc-flow/pull/4073) address #25.
Added functional test to ensure that this works properly.
Modified the logic ensuring the _only one_ template variables section is allowed.
Tests will fail online until [Cylc-flow PR 4073](https://github.com/cylc/cylc-flow/pull/4073) is merged.
> Enable `rose-suite.conf[template variables]`

- cylc/rose/entry_points.py
- tests/test_functional_post_install.py
closes #33 , and fixes a related bug.
- Stop `record_cylc_install_options` creating `rose-suite.conf` in the flow directory, unless there is one in the source directory.
- Have the config loaded by `rose_fileinstall` from the flow directory, rather than the source directory.
- Check that both the source and flow directory have valid configs in them.
> Exit `record_cylc_install_options` early if not Rose suite.

- cylc/rose/entry_points.py
- tests/conftest.py
- tests/test_functional_post_install.py
sibling: https://github.com/cylc/cylc-flow/pull/4097
Cause: Cylc rose trying to dump config where config == False.
Fix: Prevent cylc-rose dumping config if config not present.
> Fix failure of non-rose workflows

- cylc/rose/__init__.py
Create a brief of What Cylc Rose _does_.
Ideall links to content currently in [cylc-docs PR 201](https://github.com/cylc/cylc-doc/pull/201) can be added. Content should be good to review though.
> Fleshed out __init__ docs a little

- cylc/rose/__init__.py
There is no `template variables` term in the glossary. Can add later, for now easier to remove the reference to avoid beta delay.
> docs: fix broken reference

- cylc/rose/__init__.py
- setup.py
* Define the version number in the package.
* This means we can do `cylc.rose.__version__`.
* Load this version number in the `setup.py` file.
* This way we never get mismatching version numbers.
* Change the version from "1.0.0" to "0.1.0".
* Use version "0" for code that is not production ready yet.
* We will release version `1.0.0` to accompany Cylc `8.0.0` and Rose `2.0.0`.
```python
>>> import cylc.rose
>>> cylc.rose.__version__
'0.1.0'
```
> setup: load __version__ from package

- cylc/rose/__init__.py
Attempt to fix this [cylc-doc nightly build error](https://github.com/cylc/cylc-doc/runs/2661115314?check_suite_focus=true):
```
Warning, treated as error: 
unknown directive or role name: rose:ref 
make: *** [Makefile:37: html] Error 2 
```
The build process worked locally for me before and after this change, so not sure what's going on. Possibly a backwards incompatible change in a new Sphinx version?
> Fix sphinx reference

- .github/workflows/tests.yml
- cylc/rose/entry_points.py
- cylc/rose/jinja2_parser.py
- cylc/rose/stem.py
- cylc/rose/utilities.py
- mypy.ini
- setup.py
- tests/functional/test_copy_config_file.py
- tests/functional/test_pre_configure.py
- tests/functional/test_rose_fileinstall.py
- tests/functional/test_rose_stem.py
- tests/test_config_node.py
- tests/test_config_tree.py
- tests/test_functional_post_install.py
Use of `root-dir` in a rose-suite.conf raises a warning. 
This PR also fixes the flake8 issues that were causing master to fail, and fixes mypy failure too with adding `--install-types` to the GH Actions mypy command.
To test `cylc install` a workflow with a rose-suite.conf containing root-dir config. This logic existed before but was skipping e.g.
```
root-dir{share/cycle}=$TMPDIR
> check root-dir

- cylc/rose/jinja2_parser.py
Small bug spotted whilst trying to validate existing workflows with Cylc 8.
> Whitelist unary sign operators for literal_eval

- tests/functional/05_opts_set_from_rose_suite_conf/opt/rose-suite-Gaelige.conf
- tests/functional/test_pre_configure.py
Partial Response to https://github.com/cylc/cylc-flow/issues/4288
Twin of https://github.com/cylc/cylc-flow/pull/4293
Test to ensure that `cylc list` works correctly with Cylc Rose options.
Do not expect tests to pass without twin PR.
> cylc-rose: `cylc list` compatibility

- cylc/rose/__init__.py
Partial answer to https://github.com/cylc/cylc-doc/issues/170 Twinned with https://github.com/cylc/cylc-doc/pull/273
- Flesh out description of new `rose-stem` a little.
- Update description of Cylc Rose and list of Cylc utils where it is plumbed in.
> Major Changes - Cylc Install - Rose Stem

- pytest.ini
Closes #71 
Currently when functional test fails (often when it runs `cylc validate`) one has locate the pytest running that code and add breakpoints, even when the test failure relates to problems which are small or tangential to the feature in question.
By adding `-s` to the pytest option any failures will show the stdout from the commands run.
To test, try doing anything nasty (delete the runtime section/add an illegal config item/remove icp/change the name of a jinja2 template variable) to the `flow.cylc` in any of the functional test workflows and running the tests.
see also [Pytest docs: How to caputure stdout/err](https://pytest.org/en/latest/how-to/capture-stdout-stderr.html#setting-capturing-methods-or-disabling-capturing)
> disabled capturing of stderr to allow us to see cause of failure in functional tests 

- .github/workflows/1_create_release_pr.yml
- .github/workflows/shortlog.yml
- CONTRIBUTING.md
Closes #69 
Adds the following:
- A call to check shortlog action for each PR to ensure that people proactively update `CONTRIBUTING.md`.
- The same check in the creation of a release PR.
Similar to https://github.com/cylc/cylc-flow/pull/4205
To see the workflow run successfully see https://github.com/cylc/cylc-rose/runs/3359046877?check_suite_focus=true.
After a successful review and merge the reviewer should close the PR #82 and delete it's branch. Merging reviewer should also delete the `check-CONTRIBUTORS.md` branch which I used to test this work.
> check CONTRIBUTING.md against mailmap

- tests/functional/10_reinstall_basic/flow.cylc
- tests/functional/test_rose_fileinstall.py
- tests/test_rose_opts.py
This reverts commit abdcfd132e8daff94e3040ca88cc95f526f43c5e.
And therefore tests https://github.com/cylc/cylc-flow/pull/4360
**Test failure to be expected without this cylc-flow branch**
> allow failure to set templating engine _anywhere_ to pass quietly.

- cylc/rose/platform_utils.py
- tests/functional/test_pre_configure.py
Closes #83 
- Changed a test from checking exact output to looking for key-words in error message.
- Alphabetized imports (deeply sad).
> Replace `parse_workflow_arg` with `parse_reg`.

- mypy.ini
A blank `py.typed` file is needed in the package namespace otherwise some type checking might be skipped. Note that it must also be included in `setup.py` but it already is
https://github.com/cylc/cylc-rose/blob/9cd5448da318fa36fc95a4d5ab059dd185d3043b/setup.py#L63
> Add py.typed file and improve mypy config

- setup.py
* See https://github.com/cylc/cylc-admin/issues/130
> setup: pin cylc-flow version

- MANIFEST.IN
- cylc/rose/__init__.py
- setup.cfg
- setup.py
* Move metadata from setup.py to setup.cfg for simplicity.
* Keep the setup.py file, when we are ready we can remove this to switch to PEP517 build.
> setup: move project metadata to setup.cfg

- .github/workflows/tests.yml
- README.md
For the second time in a week I've found a change in Rose or Cylc has broken Cylc Rose. 
Cylc Rose is designed to link Cylc and Rose and therefore is vulnerable to changes of plugin interface.
I want to know when this happens.
> Added a nightly test and a badge on the README to match

- .github/workflows/tests.yml
- cylc/rose/stem.py
- cylc/rose/utilities.py
- setup.cfg
- tests/functional/06_jinja2_thorough/flow.cylc
- tests/functional/09_template_vars_vanilla/flow.cylc
- tests/functional/test_rose_stem.py
- tests/test_config_node.py
After doing some checks for #11 
`ROSE_VERSION` is ignored if set in `rose-suite.conf`. This PR adds a warning message for users that this is the case.
`CYLC_VERSION` is ignored by Cylc, and already has a warning message.
> Warn ROSE_VERSION in rose-suite.conf is ignored

- .github/workflows/tests.yml
I keep getting notifications whenever the tests fail on the scheduled run. This is because I merged the last PR that touched this line. If you merge this PR normally (i.e. not squash/rebase merge) then you should get the notifications from now on.
> GH Actions: Edit test schedule

- cylc/rose/utilities.py
- tests/functional/test_ROSE_ORIG_HOST.py
- tests/test_config_node.py
- tests/test_config_tree.py
Responds to an issue discovered whilst inspecting code:
At the moment Cylc Rose defers to `rose-suite.conf` when deciding whether to set `ROSE_ORIG_HOST`: The plugin should always over-ride this, warning the user if it has done so.
This may close https://github.com/cylc/cylc-rose/issues/105
> Rose orig host should warn if set in config and be over ridden

- cylc/rose/platform_utils.py
https://github.com/cylc/cylc-flow/pull/3931 deprecates `parse_reg`, replacing it with `parse_id`: This updates Cylc Rose to use the new interface.
It will neither pass tests nor should it be merged until after https://github.com/cylc/cylc-flow/pull/3931.
> Replace parse_reg with parse_id

- README.md
- cylc/rose/__init__.py
- cylc/rose/entry_points.py
- cylc/rose/platform_utils.py
- cylc/rose/utilities.py
- tests/functional/test_ROSE_ORIG_HOST.py
- tests/functional/test_reinstall.py
- tests/functional/test_reinstall_clean.py
- tests/test_config_node.py
- tests/test_config_tree.py
- tests/test_functional_post_install.py
- tests/test_rose_opts.py
Follow up #104 
Ended up with massive mission creep:
Cylc Rose should do the following with ROSE_ORIG_HOST:
- Annotate the config item in `rose-suite-cylc-install.conf` to indicate that the install process saved this config.
- Use the saved ROSE_ORIG_HOST for installed workflows.
- Make ROSE_ORIG_HOST the hostname of the machine running the script otherwise, warning the user that any value which they may have set will be over-ridden.
> Small re-write of special variables docs.

- .github/workflows/1_create_release_pr.yml
- README.md
- Add tests badge [![tests](https://github.com/cylc/cylc-rose/actions/workflows/tests.yml/badge.svg)](https://github.com/cylc/cylc-rose/actions/workflows/tests.yml) to release PRs so we can be more aware of test failures before creating a release
- Update release date in changelog (depends on #112)
> Update release workflow

- CHANGES.md
- cylc/rose/entry_points.py
- tests/functional/test_pre_configure.py
Closes #117 
@dpmatthews  - I'm tagging you here, so you get a message that I've put a PR up, but not list you as a reviewer.
> Plugin fails if CLI opts given, but workflow not a Rose suite.

- setup.cfg
`isodatetime` and `jinja2` are used explicitly and should be included in the setuptools spec. They are critical dependencies for `cylc-flow`, so must be very loosely pinned to avoid conflict with Cylc Flow.
> add explict deps for isdatetime and jinja2

- tests/functional/test_pre_configure.py
- tests/test_config_node.py
to allow changed Parsec error message to be accepted by the test.
Broken by [this comment](https://github.com/cylc/cylc-flow/pull/4720#discussion_r816516651) in #4720.
> Make test_pre_configure[template engine conflict] less specific

- CHANGES.md
- cylc/rose/entry_points.py
- cylc/rose/utilities.py
- tests/test_config_node.py
These changes close #124 
Cylc Rose was checking for `[empy:suite.rc]` and `[jinja2:suite.rc]` both being set, but was not checking whether either was being set with `[template variables]`.
Tagging @dpmatthews for a functional review as he raised this bug. IMO this only requires 1 full review +1 manual test.
> Fix.do not allow multiple templating sections

- CHANGES.md
- cylc/rose/utilities.py
- tests/test_config_tree.py
These changes close #121  and #122
The pre_configure step was not handling `cylc command -S`/`--rose-template-variable` command line option: This wasn't a problem with the `cylc install; cylc play workflow`, because the post_install step would handle this variable saving it to `opt/rose-suite-cylc-install.conf` from whence it would be picked up by `cylc play`. This meant that:
- It was possible to install variables with illegal values (#121). 
- It was impossible to validate, dump &c workflows reliant on template variables supplied by `-S` (#122).
@dpmatthews  Tagged as discoverer of these bugs.
> Pre configure not handling rose template variables properly

- cylc/rose/utilities.py
- tests/test_config_node.py
- dump rose-suite.conf in log/config not log/conf
- ensure that log/config/<timestamp>-rose-suite.conf includes a time-zone
- Closes #135
- Deliberately not done anything which might be addressed in #134 
- Only asking for a single review because it's a very small change.
> Small Changes to location of `log/x/___-rose-suite.conf`

- cylc/rose/entry_points.py
- cylc/rose/utilities.py
- tests/functional/test_pre_configure.py
- tests/test_config_node.py
These changes close https://github.com/cylc/cylc-rose/issues/123
> Log warning [jinja2/empy:suite.rc] is deprecated

- tests/functional/test_ROSE_ORIG_HOST.py
- tests/functional/test_pre_configure.py
- tests/functional/test_reinstall.py
- tests/functional/test_reinstall_clean.py
- tests/functional/test_reinstall_fileinstall.py
- tests/functional/test_rose_fileinstall.py
- tests/test_rose_opts.py
This is a small change with no associated Issue: Recent changes in the CLI for `cylc install` (https://github.com/cylc/cylc-flow/pull/4823) broke a large number of tests.
They also broke Rose Stem, but this PR does not attempt to fix this - will do that in a later PR.
**It will therefore fail tests, but only rose stem tests should fail.**
> Updated tests to use the new Cylc install CLI syntax:

- cylc/rose/jinja2_parser.py
Follow on from #140 which introduced back support for integers with leading zeros (e.g. `01`, `002`, etc).
Unfortunately the zero-stripping was a little over zealous so would strip the zero from the number `0` :facepalm:.
> jinja2: fix parsing of zeros

- cylc/rose/utilities.py
- tests/functional/test_pre_configure.py
1. Warnings referring only to Cylc 8 should not appear in Cylc 7 compatibility mode.
2. Warning about `[jinja2:suite.rc]` should make it clear that they refer to `rose-suite.conf` and use the section syntax consistently.
> Fix.deprecation message about suiterc section

- cylc/rose/utilities.py
- tests/functional/test_pre_configure.py
Added a .lower method to ensure that, as in parsec the case of the
rose section header is not considered.
A test user was spotted trying to use `rose-suite.conf[jinja2:flow.cylc]`, and was surprised to get a validation failure. Items in this section are not passed to Cylc by the plugin.
> Warn users that  `[jinja2:flow.cylc]` will not supply template vars.

- CHANGES.md
- cylc/rose/platform_utils.py
- tests/functional/test_pre_configure.py
- tests/unit/test_platform_utils.py
Closes https://github.com/metomi/rose/issues/2558
* The `get_platforms_from_task_jobs` interface was using the private
database.
* The private database is for use by the scheduler process/thread alone,
access from other connections can result in database locked errors.
> db: use the public rather than the private database

- setup.cfg
I think the reason the cylc-doc GH Actions is failing to install the libraries is the conflicting dependencies
```ini
cylc-flow==8.1.*
```
```ini
cylc-flow==8.0.*
```
I have updated the dependency on cylc-flow to `8.1.*` here, to match cylc-uiserver.
Strictly speaking this should be on the 1.2.0 milestone rather than 1.1.1. Perhaps we should create a 1.1.x branch like we've got in cylc-flow for the maintenance releases?
> Bump cylc-flow dependency

- CHANGES.md
- cylc/rose/utilities.py
- tests/functional/test_validate_no_rose_ignore_items.py
It closes an otherwise undocumented bug where variables commented in a `rose-suite.conf` (with a `!` or `!!`) are passed to Cylc regardless.
> Don't pass rose variables with state ! or !! to Cylc.

- CHANGES.md
- cylc/rose/stem.py
- tests/functional/test_rose_stem.py
- tests/unit/test_rose_stem_units.py
At Rose 2019  the command `rose stem  --source=X=$PWD` would set the variable `conf_dir` to None by default, before passing the options to the `StemRunner.process` method.
At Rose 2 I had failed to do this and as a result attempts to calculate the `conf_dir` in Rose failed because there was no `conf_dir` to reference.
n.b. In the process of translating the Rose 2019 code I renamed `conf_dir` and `source` to `source` and `stem_sources` respectively. I'm not completely happy with that decision, but I don't want to add a reversion to it to this PR.
- I've copied the Rose 2019 help docs for rose stem - they probably aren't perfect, but I've created https://github.com/cylc/cylc-rose/issues/176 to improve them.
- A bug with the target for …
> Rose Stem Fixes

- CHANGES.md
This seems to be the only way to resolve the conflict without inadvertently changing setup.cfg on master.
After this is merged, we can reopen #184
> Fix changelog conflict with 1.1.x

- setup.cfg
Because we now have different branches for metomi-rose for 2.0.x and 2.1.x (master) the dependency here (on cylc-rose master branch) has to be bumped to `2.1.*` in order for GH Actions install step to work across our different repos.
---
The alternative, seeing as there is nothing on metomi-rose master that isn't on 2.0.x (other than the `__init__.py` version number), is to roll back the `__init__.py` version number and ditch the 2.0.x branch until such a time as it is actually needed.
> Bump rose dependency to `2.1.*`

- cylc/rose/stem.py
- setup.cfg
- tests/functional/test_rose_stem.py
- tests/unit/test_rose_stem_units.py
These changes partially address #157 
I have added some unit tests designed to cover holes in the functional testing for `rose stem` I translated from Rose 2019.
added @dpmatthews  as a functional review WRT mocking subprocessed fcm commands.
> Improve rose stem coverage

- CHANGES.md
- cylc/rose/__init__.py
- cylc/rose/stem.py
- tests/unit/test_rose_stem_units.py
> feature: stem installs to workflow name not `rose-stem`

- CHANGES.md
- cylc/rose/entry_points.py
- cylc/rose/utilities.py
- tests/functional/test_reinstall.py
- tests/unit/test_config_tree.py
These changes close #191 
in `record_cylc_install_options` the function `identify_templating_section` is used to check whether the user has set more than one templating section. This is done after the previous `rose-suite-cylc-install.conf` has been merged with the new one, so that if the user has changed the templating language both will be present in the merged config and the test will always fail.
- Move checks for multiple templating sections to before old and new configs are merged
- Algorithm merging previous and current config  renames old template variables section if new install has changes it.
- Update tests for merge algorithm.
- Remove test that it's impossible to change templating languages on reinstall - it should not be.
> Allow change of templating language when reinstalling

- tests/conftest.py
- tests/functional/test_ROSE_ORIG_HOST.py
- tests/functional/test_pre_configure.py
- tests/functional/test_reinstall.py
- tests/functional/test_reinstall_clean.py
- tests/functional/test_reinstall_fileinstall.py
- tests/functional/test_rose_fileinstall.py
- tests/unit/test_rose_opts.py
Lots of tests are reliant on subprocess to run Cylc Command line scripts. In many cases this is not now necessary - Cylc offers an API for running the same script. Some of these may not work correctly until after Cylc VIP is merged
> Remove subprocess from tests

- tests/conftest.py
Allow tests to pass by fixing the interface with Cylc Validate.
> fix cylc validate interface

- CHANGES.md
- setup.cfg
Skip the `1.1.2` release, pin to metomi-rose `2.0.*` as there is no need to release `2.1.0` due to a lack of functional changes.
See https://github.com/cylc/cylc-admin/issues/162#issuecomment-1380193104
> prepare 1.2.0

- tests/functional/test_pre_configure.py
It tests https://github.com/cylc/cylc-flow/pull/5367
n.b. Expected to fail tests prior to merge of https://github.com/cylc/cylc-rose/pull/208
> Add tests for rose options being available in Cylc View

- cylc/rose/utilities.py
If these arguments are `None` rather than `[]` errors will occur in these places.
Stick a couple of `or []`'s in there to shore things up.
**Check List**
> protect against None values

- CHANGES.md
- cylc/rose/stem.py
- tests/functional/test_rose_stem.py
- tests/unit/test_rose_stem_units.py
Does not close a separate issue;
Reported by @james-bruten-mo: 
Rose stem assumes that the name of the templating section is `[jinja2:suite.rc]`. At Rose 2  `[template variables]` is preferred, though the older form is kept for back compatibility. If the new form is used in the config file rose stems use of the older form will cause one of cylc-roses checks on the config to fail.
**Check List**
> Fix.template vars section

- tests/conftest.py
for running Cylc installs.
It also fixes problems caused by changes to CLI options in Cylc.
**Check List**
IMO this is a 1-review change.
> Import Cylc option parser Options object to set up options

- tests/functional/test_rose_stem.py
Some Cylc Rose tests were creating symlinks when running `cylc_install`. This change overrides the symlinking.
Equivalent of https://github.com/cylc/cylc-flow/pull/5584
**Check List**
> Prevent tests creating symlinks on installation.

- CHANGES.md
- cylc/rose/utilities.py
- tests/conftest.py
- tests/functional/test_pre_configure.py
- tests/unit/test_config_node.py
Pull request closing an issue documented here:
This issue (https://github.com/cylc/cylc-rose/issues/230) describes a rose suite configuration which raises warnings when cylc compatibility mode is turned off. The warning that `root-dir` is no longer valid at Cylc 8 is valid whether or not compatibility mode is turned on and should be shown in either case.
**Check List**
> Permitted warnings about root-dir for all versions of Cylc.

- setup.cfg
`ansimarkup` is imported since #172 but not listed as a dependency. Hasn't caused any issues because it's a dependency of cylc-flow
> Add missing dependency on ansimarkup

- cylc/rose/stem.py
- tests/functional/test_rose_stem.py
- tests/unit/test_rose_stem_units.py
Fixes a small bug in an error printout:
How to reproduce:
```console
mkdir -p "${HOME}/example/rose-stem"
touch "${HOME}/example/rose-stem/flow.cylc"
touch "${HOME}/example/rose-stem/rose-suite.conf"
rose stem \
--source=foo="${HOME}/example"\
--workflow-name=$(uuidgen)
```
Will return an error, but at the moment the error is:
```
RoseStemVersionException: Running rose-stem version 1 but suite is does not have ROSE_VERSION set in the rose-suite.conf
```
But this is wrong and unhelpful: The variable should be ROSE_STEM_VERSION.
Additionally I've made `RoseStemVersionException` inherit `CylcError` so that we can suppress the traceback, unless in debug mode.
**Check List**
> make RoseStemVersionException print the correct missing variable

- CHANGES.md
- cylc/rose/stem.py
- tests/unit/test_rose_stem_units.py
Issue documented in code and PR.
Before `-s=name` would lead to project name being manually set to '' rather than using FCM to setup a project name. This is a correct from the point of view of optparse, but might seem surprising to users.
@dpmatthews  tagged as product owner/understand why the change.
@MetRonnie  as code review - IMO it's so trivial we shouldn't spend much time on it.
**Check List**
> Fix.rose stem name is empty string

- CONTRIBUTING.md
- cylc/rose/jinja2_parser.py
Suggested change to warning text when integers with leading zeros are encountered. 
This PR addresses issue #254 
Tests not needed because only warning text is changed.
**Check List**
> Suggested change to warning text re integers starting with a zero

- CHANGES.md
- cylc/rose/stem.py
- cylc/rose/utilities.py
- tests/unit/test_config_node.py
- tests/unit/test_rose_stem_units.py
Closes #246 
Ensure that a `:suite.rc` is added to the template language when creating defines.
**Check List**
> Stem: Make defines contain `:suite.rc`

- CHANGES.md
- cylc/rose/entry_points.py
- cylc/rose/utilities.py
Closes #226 
Built atop https://github.com/cylc/cylc-rose/pull/221
**Check List**
> Raise error if `"="` not in define

- CONTRIBUTING.md
- mypy.ini
- setup.cfg
Closes https://github.com/cylc/cylc-admin/issues/182
Added flake8-type-checking library to project
**Check List**
> added flake8-type-checking

- .coveragerc
- cylc/rose/entry_points.py
- cylc/rose/stem.py
- cylc/rose/utilities.py
- tests/unit/test_functional_post_install.py
- tests/unit/test_rose_opts.py
- tests/unit/test_rose_stem_units.py
Partial Response to https://github.com/cylc/cylc-rose/issues/157, and partial replacement of https://github.com/cylc/cylc-rose/pull/196
The aim from my point of view is to separate easy small changes from the need to refactor subprocess tests more thoroughly to work in a manner similar to Cylc's integration tests.
My checks on coverage suggest that this brings coverage from just over 95% to just under 99%
**Check List**
> improve test coverage

- .github/workflows/branch_sync.yml
- .github/workflows/tests.yml
- setup.cfg
- tests/functional/test_rose_stem.py
`pip install` is currently failing on Python 3.7 due to conflicting dependencies related to flake8.
I have separated the linting and testing dependencies and separated them into different jobs on GH Actions
> GH Actions: separate lint vs test jobs

- tests/functional/test_rose_stem.py
Prevents caching of the rose config from making some rose stem tests flaky.
As a side benefit it's a little quicker.
How to demonstrate the problem:
```console
test1="tests/functional/test_rose_fileinstall.py::test_rose_fileinstall_run"
test2="tests/functional/test_rose_stem.py::TestWithConfig"
pytest $test1 $test2
pytest $test2 $test1
```
**Check List**
> Mock user config without creating a config file.

- tests/functional/test_rose_stem.py
Small change to #289 to avoid the use of mock, and to change the Rose config object as little as possible.
> Mock only a single method of the rose config object.

- tests/functional/test_rose_stem.py
This test failed (locally) due to a local change in config. On looking into the breakage I realized that we only wanted to test that the hostname as Rose finds it is inserted into the config. We aren't trying to check the rose localhost getting method in this test.
Tests related to #276 are still failing, but should pass once that PR and it's companions are merged.
**Check List**
> use fqdn in rose-stem tests

- CHANGES.md
- cylc/rose/__init__.py
- cylc/rose/utilities.py
- tests/conftest.py
- tests/functional/test_ROSE_ORIG_HOST.py
- tests/functional/test_reinstall.py
- tests/functional/test_reinstall_clean.py
- tests/functional/test_rose_fileinstall.py
- tests/functional/test_utils.py
Closes #237 
This is now ready for review but needs testing against https://github.com/cylc/cylc-flow/pull/5839.
Ensure that the cached globalconfig object is reloaded after the export of `CYLC_SYMLINKS` variable. This means that using the `CYLC_SYMLINKS` variable allows users to specify installation symlink locations in the `rose-suite.conf`.
n.b. I was surprised to find that running `glbl_cfg()._DEFAULT = None` did not clear the cached config in a way that would force the reload in Cylc, but I think just reloading the config in Cylc Rose makes at least as much sense.
**Check List**
> Repopulate cached GlobalConfig object if CYLC_SYMLINKS exported to env.

- cylc/rose/entry_points.py
- cylc/rose/fileinstall.py
- cylc/rose/stem.py
- setup.cfg
- tests/conftest.py
- tests/functional/test_ROSE_ORIG_HOST.py
- tests/functional/test_pre_configure.py
- tests/functional/test_reinstall.py
- tests/functional/test_reinstall_clean.py
- tests/functional/test_reinstall_fileinstall.py
- tests/functional/test_rose_fileinstall.py
- tests/functional/test_rose_stem.py
- tests/functional/test_utils.py
- tests/unit/test_fileinstall.py
This is one of a triplet of PRs which closes https://github.com/cylc/cylc-rose/issues/274
* https://github.com/cylc/cylc-flow/pull/5868
* https://github.com/metomi/rose/pull/2744
---
* Rose will now take over the role of managing its event loop.
* Addresses https://github.com/cylc/cylc-rose/issues/274
---
See the cylc-flow PR for testing instructions.
**Check List**
> fileinstall: remove asyncio logic

- CHANGES.md
- cylc/rose/platform_utils.py
- tests/unit/test_platform_utils.py
* When retrieving the platform used by a task, use the processed workflow config rather than processing the config from scratch.
* This avoids the need to access the DB to extract template variables (workflow params) which could cause public DB locking issues.
**Check List**
> platforms: use processed workflow config

- cylc/rose/platform_utils.py
- tests/unit/test_platform_utils.py
Works with https://github.com/cylc/cylc-flow/pull/6097 to close https://github.com/cylc/cylc-rose/issues/319.
Functional test provided by https://github.com/metomi/rose/pull/2779
**Check List**
> Fix.cylc rose issue 319

- cylc/rose/utilities.py
- setup.cfg
Sibling: https://github.com/cylc/cylc-flow/pull/6249
* Use the new `reload` kwarg rather than calling the `.load()` method.
* Fixes https://github.com/cylc/cylc-flow/issues/6244
* The `.load()` method mutates the existing config, due to the use of logging within (and outside of) this routine and the use of `glbl_cfg` in the logging, this created a race condition.
* The new `reload` kwarg creates a new config instance, then sets this as the default.
**Check List**
> glbl_cfg: reload without mutating the original

- tests/functional/test_pre_configure.py
Test relied on changed logging output from Cylc validate.
Broken by https://github.com/cylc/cylc-flow/pull/6289
> Fix test broken by Cylc 8.4 better handling of Jinja2 error

- .github/workflows/tests.yml
* Fixes test failures.
* Get Python from conda-forge rather than the OS vendor.
* Fixes Python 3.7 tests (currently broken due to OS support).
* Test with all supported Python versions.
* Requires https://github.com/cylc/release-actions/pull/100
> actions: use mamba to provision Python environment

- CHANGES.md
- cylc/rose/stem.py
- tests/functional/test_rose_stem.py
* The `ROSE_ORIG_HOST` variable is set using the Cylc interface.
* The `HOST_SOURCE...` rose-stem variables are set using the Rose interface.
* The two interfaces differ, Cylc picks long hostnames, Rose picks short ones.
* The inconsistency may cause issues with simplistic "is this localhost" checks.
* The shortnames are causing issues at one site.
* Switch to using the Cylc interface for all scenarios.
**Check List**
> stem: use Cylc host selection interface

- changes.d/386.fix.md
- cylc/rose/platform_utils.py
- tests/unit/test_platform_utils.py
Closes https://github.com/metomi/rose/issues/2924
`rose_prune` should skip platforms that cannot be found (e.g. an invalid platform that doesn't exist).
**Check List**
> Make `rose_prune` skip platforms that cannot be found
