cylc/cylc-rose

- .github/workflows/tests.yaml
- .github/workflows/tests.yml
- cylc/rose/rose.py
- setup.cfg
- setup.py
- tests/test_rose.py
> Initialchanges

- cylc/rose/__init__.py
- setup.py
Add an `__init__.py` file for the purpose of packaging and documentation.
> add init file

- cylc/rose/entry_points.py
- cylc/rose/utilities.py
- tests/test_config_node.py
- tests/test_functional_post_install.py
> Revert "Create cylc config save file.create log rose conf"

- cylc/rose/entry_points.py
- cylc/rose/utilities.py
- tests/test_config_node.py
- tests/test_functional_post_install.py
> Revert "Revert "Create cylc config save file.create log rose conf""

- .codecov.yml
- .coveragerc
- .github/workflows/tests.yml
- cylc/rose/entry_points.py
- cylc/rose/utilities.py
- setup.py
- tests/test_config_node.py
Add code coverage and set a 100% expectation (much less audacious than it sounds).
Need to merge others first as they add both code and coverage.
> actions: test code coverage

- cylc/rose/entry_points.py
- tests/functional/test_pre_configure.py
Partially closes #37 
This PR is probably sufficient to remove the 1.0.0 milestone from #37 , but I'd like the error message to reference documentation more specifically.
I think that this is small enough a change that 1 reviewer will suffice.
> Root dir warning

- cylc/rose/entry_points.py
- setup.cfg
- tests/functional/test_copy_config_file.py
- tests/test_rose_opts.py
Closes #36, when run in combination with [cylc-flow PR 4094](https://github.com/cylc/cylc-flow/pull/4094)
> AAA_Install rose suite.conf in cylc rose

- .github/workflows/tests.yml
- cylc/rose/utilities.py
- mypy.ini
- pytest.ini
- setup.py
Was getting a type error raised up in the cylc-flow tests. Mypy will help catch these things in future.
See https://github.com/cylc/cylc-flow/pull/4121 for more on the Mypy implementation.
> Fix type error and start to add mypy / type annotations

- cylc/rose/__init__.py
> Init  .docs

- cylc/rose/stem.py
- tests/functional/06_jinja2_thorough/flow.cylc
- tests/functional/09_template_vars_vanilla/flow.cylc
- tests/functional/test_rose_stem.py
> give Cylc install the correct options

- setup.cfg
Needed to add some metadata for PyPi etc, see Cylc & Rose for context.
Could potentially overwrite the existing release, else can have a maintenance release.
> setup: add metadata

- .gitignore
- cylc/rose/__init__.py
- cylc/rose/entry_points.py
- cylc/rose/jinja2_parser.py
- cylc/rose/utilities.py
- setup.cfg
- setup.py
- tests/conftest.py
- tests/functional/02_env/flow.cylc
- tests/functional/10_reinstall_basic/flow.cylc
- tests/functional/test_copy_config_file.py
- tests/functional/test_pre_configure.py
- tests/functional/test_reinstall.py
- tests/functional/test_reinstall_clean.py
- tests/functional/test_rose_fileinstall.py
- tests/test_config_node.py
- tests/test_config_tree.py
- tests/test_functional_post_install.py
- tests/test_generic_utils.py
- tests/test_rose_opts.py
Companion of https://github.com/cylc/cylc-flow/pull/4174, https://github.com/cylc/cylc-flow/pull/4198
> suite -> workflow

- tests/functional/test_pre_configure.py
companion to https://github.com/cylc/cylc-flow/pull/4212
> updated error msg in test

- .github/workflows/1_create_release_pr.yml
- .github/workflows/2_auto_publish_release.yml
Closes #4 
Are there any steps unique to cylc-rose I have missed out?
> Implement GH Actions automated release process

- tests/functional/10_reinstall_basic/flow.cylc
- tests/functional/test_rose_fileinstall.py
- tests/test_rose_opts.py
Should fix testing failures.
Mutually exclusive https://github.com/cylc/cylc-flow/pull/4337
> fix tests where Cylc Flow is missing a shebang

- CONTRIBUTING.md
Thanks @wxtim for pointing out I hadn't done it before, sorry. One review should do.
> Add myself as contributor

- cylc/rose/utilities.py
- tests/test_config_tree.py
check whether workflow is a rose suite now can take CLI options to support workflow being a suite if rose CLI vars passed
Paired with https://github.com/cylc/cylc-flow/pull/4502
> cylc-rose run twice bug

- .github/workflows/tests.yml
- README.md
- cylc/rose/stem.py
- setup.cfg
- tests/functional/test_rose_stem.py
Following https://github.com/metomi/rose/pull/2494 it will be possible to register `stem` as a `rose` command.
> rose stem without the hyphen

- cylc/rose/stem.py
Rose Stem broke after https://github.com/metomi/rose/pull/2509 - this fixes.
> fix breakage caused by rose popener always returning decoded str

- .github/workflows/tests.yml
- pytest.ini
- setup.cfg
Need to do an editable pip install (`-e`) for coverage to work
> Fix coverage; use flake8-simplify; update GH Actions

- .github/workflows/shortlog.yml
- .mailmap
- CONTRIBUTING.md
Update mailmap to avoid WXTIM appearing.
> fix mailmap

- cylc/rose/__init__.py
- setup.cfg
```
cylc-rose 1.0.4.dev
```
```
cylc-flow 8.0rc4.*
metomi-rose 2.0rc4.*
```
> Bump versions

- pytest.ini
Doc tests were not set up to run with pytest.
> Add doc tests to pytest

- .codecov.yml
- .github/dependabot.yml
- .github/workflows/tests.yml
These changes close #156
This should add Codecov checks to PRs, plus enable Dependabot PRs
> Update codecov config + add dependabot config

- cylc/rose/utilities.py
- tests/functional/test_rose_stem.py
Suggest @MetRonnie  be single reviewer because 
- change is tiny
- you found fix independently
> Unset environment variable set in doctests.

- cylc/rose/utilities.py
- tests/conftest.py
- tests/functional/test_rose_stem.py
> Improve test cleanup

- tests/functional/test_ROSE_ORIG_HOST.py
- tests/functional/test_reinstall.py
- tests/functional/test_reinstall_clean.py
- tests/functional/test_reinstall_fileinstall.py
- tests/functional/test_rose_fileinstall.py
- tests/functional/test_rose_stem.py
- tests/unit/test_rose_opts.py
These changes close #168 
Suggestions
- run `watch -n .3 ls ~/cylc-run/cylc-rose-* then in another terminal `pytest tests/functional`
- Break some of the changed tests (`assert 1==0` should do it) and check that the info is left behind.
> functional tests only cleanup if succeeded

- cylc/rose/__init__.py
Forgot to include this in #173
> Bump dev version on master to next minor release

- cylc/rose/stem.py
> Review rose stem docs

- tests/functional/test_reinstall.py
These changes contain a test for the issue described in https://github.com/cylc/cylc-flow/pull/5125
> reinstall changes to `rose-suite.conf` [tests]

- cylc/rose/utilities.py
- tests/unit/test_config_node.py
- tests/unit/test_platform_utils.py
- tox.ini
Fix automated tests:
- Fix a flake8 issue
- Fix an SQL issue caused by more stringent database checks.
> fix flake 8 breakage

- .github/workflows/tests.yml
Use the centrally defined meta-release management thinggy for installing Cylc components from the correct branches.
> use install-cylc-components action

- CHANGES.md
- cylc/rose/stem.py
- tests/conftest.py
- tests/functional/test_rose_stem.py
- tests/unit/test_rose_stem_units.py
> Merge changes from 1.2.x → Master

- .github/workflows/1_create_release_pr.yml
- .github/workflows/2_auto_publish_release.yml
- .github/workflows/tests.yml
> actions: test up to python 3.11

- tests/unit/test_platform_utils.py
One Line flake8 bugbear fix.
Probably only needs one review.
> Fix linter objections to expression tuples.

- setup.cfg
* Rose 2.2 has only one major change vs 2.1.
* We do not need a new minor cylc-rose release for this.
Normally we would make a new minor release, that would be a bit of a pain this time around, this allows newer Rose to be used with older cylc-rose/cylc-flow.
**Check List**
-  [x] Applied any dependency changes to both `setup.cfg` (and `conda-environment.yml` if present).
> setup: permit Rose 2.2

- cylc/rose/jinja2_parser.py
De-flaky a test, there are no symptoms of this issue in normal cylc/cylc-rose usage.
> tests: fix flaky text

- setup.cfg
- tests/conftest.py
- tests/functional/test_rose_stem.py
I'm planning to work on rose-stem with #205 so trying to get to grips with the tests. This:
* Simplifies the tests.
* Links them to their original source (metomi/rose).
* *Attempts* to give them meaningful names/descriptions.
Changes outlined in the commit messages.
Supersedes #268
**Check List**
> simplify rose stem tests

- CHANGES.md
> 1.3.x sync

- setup.cfg
> bump required cylc version

- CHANGES.md
> correct changelog

- .github/workflows/shortlog.yml
Mirror https://github.com/metomi/rose/pull/2911
> Actions: run shortlog weekly

- cylc/rose/__init__.py
> Bump dev version to 1.7.0.dev
